### ISSUE TITLE
requirements.txt does not have versions

### ISSUE THREAD

**Issue by nolyn** [IENT/RDPlot#42] opened 2021-09-13 14:10 UTC
I tried to run rdplot with an venv using python 3.7 and installing requirements (in src/rdplot) using pip. it could open the application, but it crashed when selecting curves. Needed to downgrade matplotlib to 3.2.2. 
Maybe we should add the version information to the requirements.txt. Ideally this should then match whatever exact versions are used to build pipx or windows installer packages.

**Comment by JensAc** [comment] 2021-09-14 13:54
I think this is only true for matplotlib. In setup.py `matplotlib=3.4.2` is required and that should work as well. IMHO, we could add the version number for matplotlib. 
Can you just check, whether `3.4.2` also works for you?

**Comment by dmehlem** [comment] 2023-10-15 14:38
For me `rdplot` also crashes when selecting more than one curve, but I do not think the problem is related to the matplotlib version. The error message I get is:`TypeError: setRowCount(self, rows: int): argument 1 has unexpected type 'float'`

https://github.com/IENT/RDPlot/blob/443cdf168aa9220f44e6079d9b289b04208dba20/src/rdplot/Widgets/MainWindow.py#L566

This can easily be fixed by a typecast to `int()`.

However, `tikzplotlib` is currently not compatible with `matplotlib>=3.8.0` as some private methods from `matplotlib` which `tikzplotlib` uses have been deleted.

**Closed as completed** 2023-10-15 17:37 UTC
